🚧 Allow to disable SSL
kintoproj/kinto-helm pull request #15
Opened 2021-02-27 19:59 UTC by bappr

- no need to deploy cert-manager
- it will not create any certificates

2021-02-28 15:35 UTC, sumitkolhe requested changes
Just minor typo changes

2021-02-28 15:35 UTC, sumitkolhe commented on README.md
> +- Kubernetes cluster with at least a node having 4GB or more memory.
typo: 
- at least a node -> at least one node
- having 4GB or more memory -> having 4GB memory or more.

2021-02-28 15:35 UTC, sumitkolhe commented on README.md
> +Check that argo is running fine.
typo -
- check that -> check if

2021-02-28 15:35 UTC, sumitkolhe commented on README.md
> +- You must have a domain name ready to be used. KintoHub only support Cloudflare at the moment, you can create a free account and transfer your domain ownership easily. Please create an issue if you
typo - 
- only support -> only supports

2021-02-28 15:35 UTC, sumitkolhe commented on README.md
> +Check cert-manager is running fine.
typo - 
- check cert-manager -> check if cert-manager

2021-02-28 17:33 UTC, bappr commented
@sumitkolhe all your comments have been fixed, please review again. Thanks!

2021-03-01 04:21 UTC, sumitkolhe approved these changes
LGTM

2021-03-01 11:43 UTC, merged